[package]
name = "rnscripter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pollster = "0.3.0"
wgpu = "0.19.3"
winit = "0.29.15"
